App.UI/ViewModels/ExpenseCategory/ExpenseCategoryViewModel.cs
namespace App.UI.ViewModels.ExpenseCategory
{
    public class ExpenseCategoryViewModel
    {
        public int Id { get; set; }
        public string ExpenseCategoryName { get; set; }
        public string UserId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

App.UI/Controllers/ExpenseCategoryController.cs
using App.BLL.DTOs;
using App.BLL.IServices;
using App.Domain.Entities;
using App.UI.CRUDModels.ExpenseCategory;
using App.UI.ViewModels.ExpenseCategory;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace App.UI.Controllers
{
    public class ExpenseCategoryController : Controller
    {
        private readonly IExpenseCategoryService _expenseCategoryService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ExpenseCategoryController(IExpenseCategoryService expenseCategoryService, UserManager<ApplicationUser> userManager)
        {
            _expenseCategoryService = expenseCategoryService;
            _userManager = userManager;
        }

        //READ: List all expense categories
        public Task<IActionResult> Index()
        {
            var expenseCategories = _expenseCategoryService.GetAllExpenseCategoriesAsync().Result;
            var model = expenseCategories.Select(expenseCategory => new ExpenseCategoryViewModel
            {
                Id = expenseCategory.Id,
                ExpenseCategoryName = expenseCategory.ExpenseCategoryName,
                UserId = expenseCategory.UserId,
                CreatedDate = expenseCategory.CreatedDate
            });

            return Task.FromResult((IActionResult)View(model));
        }

        //CREATE: GET
        public async Task<IActionResult> Create()
        {
            var users = await _userManager.Users.ToListAsync();

            var model = new ExpenseCategoryCRUDModel
            {
                Users = users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                })
            };

            return await Task.FromResult((IActionResult)View(model));
        }

        //CREATE: POST
        [HttpPost]
        public async Task<IActionResult> Create(ExpenseCategoryCRUDModel expenseCategoryCRUDModel)
        {
            var expenseCategoryDTO = new ExpenseCategoryDTO
            {
                ExpenseCategoryName = expenseCategoryCRUDModel.ExpenseCategoryName,
                UserId = expenseCategoryCRUDModel.UserId
            };
            await _expenseCategoryService.AddExpenseCategoryAsync(expenseCategoryDTO);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }

        //UPDATE: GET
        public async Task<IActionResult> Update(int id)
        {
            var expenseCategoryToUpdate = await _expenseCategoryService.GetExpenseCategoryByIdAsync(id);
            var users = await _userManager.Users.ToListAsync();

            return await Task.FromResult((IActionResult)
                View(new ExpenseCategoryCRUDModel
                {
                    Id = expenseCategoryToUpdate.Id,
                    ExpenseCategoryName = expenseCategoryToUpdate.ExpenseCategoryName,
                    Users = users.Select(u => new SelectListItem
                    {
                        Value = u.Id,
                        Text = u.UserName
                    })
                }
                )
            );
        }

        //UPDATE: POST
        [HttpPost]
        public async Task<IActionResult> Update(ExpenseCategoryCRUDModel expenseCategoryCRUDModel)
        {
            var expenseCategoryDTO = new ExpenseCategoryDTO
            {
                Id = expenseCategoryCRUDModel.Id,
                ExpenseCategoryName = expenseCategoryCRUDModel.ExpenseCategoryName,
                UserId = expenseCategoryCRUDModel.UserId
            };
            await _expenseCategoryService.UpdateExpenseCategoryAsync(expenseCategoryDTO);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }

        //DELETE: GET
        public async Task<IActionResult> Delete(int id)
        {
            var expenseCategoryToDelete = await _expenseCategoryService.GetExpenseCategoryByIdAsync(id);
            return await Task.FromResult((IActionResult)
                View(new ExpenseCategoryCRUDModel
                {
                    Id = expenseCategoryToDelete.Id,
                    ExpenseCategoryName = expenseCategoryToDelete.ExpenseCategoryName
                }));
        }

        //DELETE: POST
        [HttpPost]
        public async Task<IActionResult> Delete(ExpenseCategoryCRUDModel expenseCategoryCRUDModel)
        {
            await _expenseCategoryService.DeleteExpenseCategoryAsync(expenseCategoryCRUDModel.Id);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }
    }
}

App.UI/Views/ExpenseCategory/Create.cshtml
@model App.UI.CRUDModels.ExpenseCategory.ExpenseCategoryCRUDModel
@{
    ViewData["Title"] = "Create Category";
}

<h1 class="display-1 text-center">Create Expense Category</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="ExpenseCategory" asp-action="Create" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryName">Name</label>
        <input asp-for="ExpenseCategoryName" class="form-control" />
        <span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control">
            <option value="">Select User</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Create</button>
    <a class="btn btn-dark" asp-controller="ExpenseCategory" asp-action="Index">Back to List</a>
</form>

App.UI/Views/ExpenseCategory/Delete.cshtml
@model App.UI.CRUDModels.ExpenseCategory.ExpenseCategoryCRUDModel
@{
    ViewData["Title"] = "Delete Category";
}

<h1 class="display-1 text-center">Delete Expense Category</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="ExpenseCategory" asp-action="Delete" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryName">Name</label>
        <input asp-for="ExpenseCategoryName" class="form-control" disabled/>
        <span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control" disabled>
            <option value=""></option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-danger">Delete</button>
    <a class="btn btn-dark" asp-controller="ExpenseCategory" asp-action="Index">Back to List</a>
</form>

App.UI/Views/ExpenseCategory/Index.cshtml
@model IEnumerable<App.UI.ViewModels.ExpenseCategory.ExpenseCategoryViewModel>
@{
    ViewData["Title"] = "Expense Categories";
}

<h1 class="display-1 text-center">Expense Categories Panel</h1>
<a class="btn btn-dark" asp-controller="ExpenseCategory" asp-action="Create">Create Category</a>
<a class="btn btn-secondary" asp-controller="Admin" asp-action="Index">Back to Admin Panel</a>
<table class="table table-striped table-bordered mt-4">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                User Id
            </th>
            <th>
                Created At
            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var category in Model)
        {
            <tr>
                <td>
                    @category.Id
                </td>
                <td>
                    @category.ExpenseCategoryName
                </td>
                <td>
                    @category.UserId
                </td>
                <td>
                    @category.CreatedDate.ToShortDateString()
                </td>
                <td>
                    <a class="btn btn-warning w-100" asp-controller="ExpenseCategory" asp-action="Update" asp-route-id="@category.Id">Update</a>
                </td>
                <td>
                    <a class="btn btn-danger w-100" asp-controller="ExpenseCategory" asp-action="Delete" asp-route-id="@category.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

App.UI/Views/ExpenseCategory/Update.cshtml
@model App.UI.CRUDModels.ExpenseCategory.ExpenseCategoryCRUDModel
@{
    ViewData["Title"] = "Update Category";
}

<h1 class="display-1 text-center">Update Expense Category</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="ExpenseCategory" asp-action="Update" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryName">Name</label>
        <input asp-for="ExpenseCategoryName" class="form-control" />
        <span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control">
            <option value="">Select User</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Update</button>
    <a class="btn btn-dark" asp-controller="ExpenseCategory" asp-action="Index">Back to List</a>
</form>