App.UI/ViewModels/Expense/ExpenseViewModel.cs
namespace App.UI.ViewModels.Expense
{
    public class ExpenseViewModel
    {
        public int Id { get; set; }
        public string ExpenseName { get; set; }
        public decimal Amount { get; set; }
        public DateTime ExpenseDate { get; set; }
        public int? ExpenseCategoryId { get; set; }
        public string ExpenseCategoryName { get; set; }
        public string UserId { get; set; }
    }
}

App.UI/Controllers/ExpenseController.cs
using App.BLL.DTOs;
using App.BLL.IServices;
using App.UI.CRUDModels.Expense;
using App.UI.ViewModels.Expense;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace App.UI.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IExpenseCategoryService _expenseCategoryService;
        private readonly IUserService _userService;

        public ExpenseController(IExpenseService expenseService, IExpenseCategoryService expenseCategoryService, IUserService userService)
        {
            _expenseService = expenseService;
            _expenseCategoryService = expenseCategoryService;
            _userService = userService;
        }

        //GET: List all expenses
        public async Task<IActionResult> Index()
        {
            var expenses = await _expenseService.GetAllExpensesAsync();
            var expenseCategories = await _expenseCategoryService.GetAllExpenseCategoriesAsync();

            var expenseList = new List<ExpenseViewModel>();

            foreach (var expense in expenses)
            {
                var expenseListItem = new ExpenseViewModel
                {
                    Id = expense.Id,
                    ExpenseName = expense.ExpenseName,
                    Amount = expense.Amount,
                    ExpenseDate = expense.ExpenseDate,
                    ExpenseCategoryId = expense.ExpenseCategoryId,
                    ExpenseCategoryName = expenseCategories.FirstOrDefault(e => e.Id == expense.ExpenseCategoryId).ExpenseCategoryName,
                    UserId = expense.UserId
                };

                expenseList.Add(expenseListItem);
            }

            return await Task.FromResult((IActionResult)View(expenseList));
        }

        //GET: CREATE
        public async Task<IActionResult> Create()
        {
            var expenseCategories = await _expenseCategoryService.GetAllExpenseCategoriesAsync();
            var users = await _userService.GetAllUsersAsync();

            var model = new ExpenseCRUDModel
            {
                ExpenseCategories = expenseCategories.Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.ExpenseCategoryName
                }),
                Users = users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                })
            };
            return await Task.FromResult((IActionResult)View(model));
        }

        //POST: CREATE
        [HttpPost]
        public async Task<IActionResult> Create(ExpenseCRUDModel model)
        {
            var expenseDTO = new ExpenseDTO
            {
                ExpenseName = model.ExpenseName,
                Amount = model.Amount,
                ExpenseDate = model.ExpenseDate,
                ExpenseCategoryId = (int)model.ExpenseCategoryId!,
                UserId = model.UserId
            };

            await _expenseService.AddExpenseAsync(expenseDTO);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }

        //GET: UPDATE
        public async Task<IActionResult> Update(int id)
        {
            var expense = await _expenseService.GetExpenseByIdAsync(id);
            var expenseCategories = await _expenseCategoryService.GetAllExpenseCategoriesAsync();
            var users = await _userService.GetAllUsersAsync();

            var model = new ExpenseCRUDModel
            {
                ExpenseCategories = expenseCategories.Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.ExpenseCategoryName
                }),
                Users = users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                }),
                Id = expense.Id,
                ExpenseName = expense.ExpenseName,
                Amount = expense.Amount,
                ExpenseDate = expense.ExpenseDate,
                ExpenseCategoryId = expense.ExpenseCategoryId,
                UserId = expense.UserId
            };

            return await Task.FromResult((IActionResult)View(model));
        }

        //POST: UPDATE
        [HttpPost]
        public async Task<IActionResult> Update(ExpenseCRUDModel model)
        {
            var expenseDTO = new ExpenseDTO
            {
                Id = model.Id,
                ExpenseName = model.ExpenseName,
                Amount = model.Amount,
                ExpenseDate = model.ExpenseDate,
                ExpenseCategoryId = (int)model.ExpenseCategoryId!,
                UserId = model.UserId
            };
            await _expenseService.UpdateExpenseAsync(expenseDTO);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }

        //GET: DELETE
        public async Task<IActionResult> Delete(int id)
        {
            var expense = await _expenseService.GetExpenseByIdAsync(id);
            var expenseCategories = await _expenseCategoryService.GetAllExpenseCategoriesAsync();
            var users = await _userService.GetAllUsersAsync();

            var model = new ExpenseCRUDModel
            {
                ExpenseCategories = expenseCategories.Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.ExpenseCategoryName
                }),
                Users = users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                }),
                Id = expense.Id,
                ExpenseName = expense.ExpenseName,
                Amount = expense.Amount,
                ExpenseDate = expense.ExpenseDate,
                ExpenseCategoryId = expense.ExpenseCategoryId,
                UserId = expense.UserId
            };

            return await Task.FromResult((IActionResult)View(model));
        }

        //POST: DELETE
        [HttpPost]
        public async Task<IActionResult> Delete(ExpenseCRUDModel model)
        {
            var id = model.Id;
            await _expenseService.DeleteExpenseAsync(id);
            return await Task.FromResult((IActionResult)RedirectToAction("Index"));
        }
    }
}

App.UI/Views/Expense/Create.cshtml
@model App.UI.CRUDModels.Expense.ExpenseCRUDModel
@{
    ViewData["Title"] = "Create Expense";
}

<h1 class="display-1 text-center">Create Expense</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Expense" asp-action="Create" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseName">Expense Name</label>
        <input asp-for="ExpenseName" class="form-control" />
        <span asp-validation-for="ExpenseName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Amount">Amount</label>
        <input asp-for="Amount" class="form-control" type="number" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseDate">Expense Date</label>
        <input asp-for="ExpenseDate" class="form-control" type="date" value="@DateTime.Now"/>
        <span asp-validation-for="ExpenseDate" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryId">Expense Category</label>
        <select asp-for="ExpenseCategoryId" asp-items="Model.ExpenseCategories" class="form-control">
            <option value="">Select Category</option>
        </select>
        <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control">
            <option value="">Select User</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Create</button>
    <a class="btn btn-dark" asp-controller="Expense" asp-action="Index">Back to List</a>
</form>

App.UI/Views/Expense/Delete.cshtml
@model App.UI.CRUDModels.Expense.ExpenseCRUDModel
@{
    ViewData["Title"] = "Delete Expense";
}

<h1 class="display-1 text-center">Delete Expense</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Expense" asp-action="Delete" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseName">Expense Name</label>
        <input asp-for="ExpenseName" class="form-control" disabled />
        <span asp-validation-for="ExpenseName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Amount">Amount</label>
        <input asp-for="Amount" class="form-control" type="number" disabled />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseDate">Expense Date</label>
        <input asp-for="ExpenseDate" class="form-control" type="date" value="@DateTime.Now" disabled />
        <span asp-validation-for="ExpenseDate" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryId">Expense Category</label>
        <select asp-for="ExpenseCategoryId" asp-items="Model.ExpenseCategories" class="form-control" disabled>
            <option value="">Select Category</option>
        </select>
        <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control" disabled>
            <option value="">Select User</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-danger">Delete</button>
    <a class="btn btn-dark" asp-controller="Expense" asp-action="Index">Back to List</a>
</form>

App.UI/Views/Expense/Index.cshtml
@model IEnumerable<App.UI.ViewModels.Expense.ExpenseViewModel>
@{
    ViewData["Title"] = "Expenses";
}
<h1 class="display-1 text-center">Expenses Panel</h1>
<a class="btn btn-dark" asp-controller="Expense" asp-action="Create">Create Expense</a>
<a class="btn btn-secondary" asp-controller="Admin" asp-action="Index">Back to Admin Panel</a>
<table class="table table-striped table-bordered mt-4">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Amount
            </th>
            <th>
                Date
            </th>
            <th>
                Category
            </th>
            <th>
                CategoryId
            </th>
            <th>
                UserId
            </th>
            <th>
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var expense in Model)
        {
            <tr>
                <td>
                    @expense.Id
                </td>
                <td>
                    @expense.ExpenseName
                </td>
                <td>
                    @expense.Amount
                </td>
                <td>
                    @expense.ExpenseDate.ToShortDateString()
                </td>
                <td>
                    @expense.ExpenseCategoryName
                </td>
                <td>
                    @expense.ExpenseCategoryId
                </td>
                <td>
                    @expense.UserId
                </td>
                <td>
                    <a class="btn btn-warning w-100" asp-controller="Expense" asp-action="Update" asp-route-id="@expense.Id">Update</a>
                </td>
                <td>
                    <a class="btn btn-danger w-100" asp-controller="Expense" asp-action="Delete" asp-route-id="@expense.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

App.UI/Views/Expense/Update.cshtml
@model App.UI.CRUDModels.Expense.ExpenseCRUDModel
@{
    ViewData["Title"] = "Update Expense";
}

<h1 class="display-1 text-center">Update Expense</h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Expense" asp-action="Update" method="post">
    <div class="form-group mb-3">
        <label asp-for="ExpenseName">Expense Name</label>
        <input asp-for="ExpenseName" class="form-control" />
        <span asp-validation-for="ExpenseName" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Amount">Amount</label>
        <input asp-for="Amount" class="form-control" type="number" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseDate">Expense Date</label>
        <input asp-for="ExpenseDate" class="form-control" type="date" value="@DateTime.Now"/>
        <span asp-validation-for="ExpenseDate" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ExpenseCategoryId">Expense Category</label>
        <select asp-for="ExpenseCategoryId" asp-items="Model.ExpenseCategories" class="form-control">
            <option value="">Select Category</option>
        </select>
        <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="UserId">User</label>
        <select asp-for="UserId" asp-items="Model.Users" class="form-control">
            <option value="">Select User</option>
        </select>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Update</button>
    <a class="btn btn-dark" asp-controller="Expense" asp-action="Index">Back to List</a>
</form>