App.UI/Controllers/UserController.cs
using App.BLL.DTOs;
using App.BLL.IServices;
using App.Domain.Entities;
using App.UI.Areas.Identity.Pages.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace App.UI.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;

        public UserController(UserManager<ApplicationUser> userManager, IUserService userService)
        {
            _userManager = userManager;
            _userService = userService;
        }

        //READ: List all users
        public async Task<IActionResult> Index()
        {
            return await Task.FromResult(View(_userManager.Users));
        }

        //UPDATE: GET
        public async Task<IActionResult> Update(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        //UPDATE: POST
        [HttpPost]
        public async Task<IActionResult> Update(ApplicationUser applicationUser)
        {
            var userToUpdate = await _userManager.FindByIdAsync(applicationUser.Id);
            if (userToUpdate == null) return NotFound();

            userToUpdate.UserName = applicationUser.UserName;
            await _userService.UpdateUserAsync(new UserDTO
            {
                Id = userToUpdate.Id,
                UserName = userToUpdate.UserName
            });

            return RedirectToAction("Index");
        }

        //DELETE: GET
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        //DELETE: POST
        [HttpPost]
        public async Task<IActionResult> Delete(UserDTO userDTO)
        {
            var userToDelete = await _userManager.FindByIdAsync(userDTO.Id);
            if (userToDelete == null) return NotFound();

            await _userService.DeleteUserAsync(userDTO.Id);
            return RedirectToAction("Index");
        }
    }
}

App.UI/Views/User/Delete.cshtml
@using App.Domain.Entities
@model ApplicationUser
@{
    ViewData["Title"] = "Delete";
}

<h3 class="display-3 text-center">Delete User</h3>
<form asp-controller="User" asp-action="Delete" method="post">
    <input type="hidden" value="@Model.Id" />

    <div class="form-group mb-3">
        <label asp-for="UserName">Username</label>
        <input asp-for="UserName" class="form-control" disabled/>
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-lg btn-danger">Delete</button>
    <a class="btn btn-lg btn-secondary" asp-controller="User" asp-action="Index">Back to Users</a>
</form>

App.UI/Views/User/Index.cshtml
@using App.Domain.Entities
@model IEnumerable<ApplicationUser>

@{
    ViewData["Title"] = "Users";
}

<h1 class="display-1 text-center">Users Panel</h1>
<a class="btn btn-secondary mb-3" asp-controller="Admin" asp-action="Index">Back to Admin Panel</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Username
            </th>
            <th>
                
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    @user.Id
                </td>
                <td>
                    @user.UserName
                </td>
                <td>
                    <a class="btn btn-warning w-100" asp-controller="User" asp-action="Update" asp-route-id="@user.Id">Edit</a>
                </td>
                <td>
                    <a class="btn btn-danger w-100" asp-controller="User" asp-action="Delete" asp-route-id="@user.Id">Delete</a>
                </td>
            </tr>
        }
</table>

App.UI/Views/User/Update.cshtml
@using App.Domain.Entities
@model ApplicationUser
@{
    ViewData["Title"] = "Edit";
}

<h3 class="display-3 text-center">Edit User</h3>
<form asp-controller="User" asp-action="Update" method="post">
    <input type="hidden" value="@Model.Id" />

    <div class="form-group mb-3">
        <label asp-for="UserName">Username</label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-lg btn-success">Update</button>
    <a class="btn btn-lg btn-secondary" asp-controller="User" asp-action="Index">Back to Users</a>
</form>